---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pttg-ip-audit
  labels:
    version: {{.VERSION}}
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pttg-ip-audit
  strategy:
    rollingUpdate:
      maxUnavailable: 0%
      maxSurge: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: pttg-ip-audit
        version: {{.VERSION}}
    spec:
      imagePullSecrets:
        - name: registrykey
      containers:
        - name: proxy
          image: quay.io/ukhomeofficedigital/nginx-proxy:v3.2.9
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          resources:
            limits:
              memory: "100Mi"
              cpu: 100m
            requests:
              memory: "50Mi"
              cpu: 100m
          env:
            - name: PROXY_SERVICE_HOST
              value: '127.0.0.1'
            - name: PROXY_SERVICE_PORT
              value: '8080'
            - name: NAXSI_USE_DEFAULT_RULES
              value: 'FALSE'
            - name: ENABLE_UUID_PARAM
              value: 'FALSE'
            - name: HTTPS_REDIRECT
              value: 'FALSE'
            - name: BASIC_AUTH
              value: /etc/nginx/service-secrets/.htpasswd_1
            - name: SERVER_CERT
              value: /certs/tls.crt
            - name: SERVER_KEY
              value: /certs/tls.key
            - name: ADD_NGINX_LOCATION_CFG
              value: 'proxy_read_timeout 99999s; proxy_connect_timeout 60s;'
            - name: ADD_NGINX_SERVER_CFG
              value: 'gzip off; location = /reload { allow 127.0.0.1; deny all; content_by_lua_block { os.execute("touch /tmp/nginx-reload-triggered; /usr/local/openresty/nginx/sbin/nginx -s reload; touch /tmp/nginx-reload-complete;") } }'
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
            - name: secrets
              mountPath: /etc/nginx/secrets
              readOnly: true
            - name: service-secrets
              mountPath: /etc/nginx/service-secrets
              readOnly: true
          ports:
            - name: https
              containerPort: 10443

        - name: pttg-ip-audit
          image: quay.io/ukhomeofficedigital/pttg-ip-audit:{{.VERSION}}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          env:
            - name: JAVA_OPTS
              value: '-Xms150m -Xmx250m'
            - name: SERVER_PORT
              value: '8080'
            - name: ENDPOINTS_INFO_ENABLED
              value: 'false'
            - name: SPRING_PROFILES_ACTIVE
              value: 'postgres'
            - name: PTTG_DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: endpoint
            - name: PTTG_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: port
            - name: PTTG_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-{{.ENVIRONMENT}}-rds
                  key: db_name
            - name: IP_SCHEMA_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: schema_name
            - name: IP_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: application_username
            - name: IP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: application_password
            - name: AUDITING_DEPLOYMENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 1600m
              memory: 612Mi
            requests:
              cpu: 100m
              memory: 484Mi
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: X-probe
                  value: kubelet
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: X-probe
                  value: kubelet
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          volumeMounts:
            - name: keystore
              mountPath: /etc/keystore
              readOnly: true
      volumes:
        - name: keystore
          emptyDir:
            medium: "Memory"
        - name: certs
          secret:
            secretName: {{ .DEPLOYMENT_NAME }}-service-tls-cmio
        - name: bundle
          configMap:
            name: bundle
        - name: secrets
          emptyDir:
            medium: "Memory"
        - name: service-secrets
          secret:
            secretName: pttg-audit-service-secrets
            items:
            - key: .htpasswd_1
              path: .htpasswd_1
